language: android
sudo: false
#JDK
jdk: oraclejdk8
notifications:
  email:
    recipients:
      - alice.pottier@free.fr
      - aud.stephan@gmail.com
      - camleuregans@gmail.com
      - coralinebouri@gmail.com
    on_success: change
    on_failure: change
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-25
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
on:
  branch: dev
before_script:
- echo no | android create avd --force -n test -t android-25 --abi x86
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &