language: android
sudo: false
#JDK
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=24
    - EMULATOR_API=25
    - ANDROID_BUILD_TOOLS=25.0.0
notifications:
  email:
    recipients:
      - alice.pottier@free.fr
      - aud.stephan@gmail.com
      - camleuregans@gmail.com
      - coralinebouri@gmail.com
    on_success: change
    on_failure: change
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-$ANDROID_API_LEVEL
    - sys-img-x86-android-$EMULATOR_API_LEVEL
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
on:
  branch: dev