language: android
sudo: false
#JDK
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=24
    - EMULATOR_API=25
    - ANDROID_BUILD_TOOLS=25.0.0
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
notifications:
  email:
    recipients:
      - lhysaara@gmail.com
      - aud.stephan@gmail.com
      - camleuregans@gmail.com
      - coralinebouri@gmail.com
    on_success: change
    on_failure: change
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-$ANDROID_API_LEVEL
    - sys-img-x86-android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-22
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-preview-license'
    - 'android-sdk-license-.+'
    - 'android-sdk-license'
    - 'google-gdk-license-.+'
before_install:
- chmod +x gradlew
- bash .travis-android-license-bugfix.sh
# Emulator Management: Create, Start and Wait
#before_script:
#- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#- emulator -avd test -no-audio -no-window &
#- android-wait-for-emulator
#- adb shell input keyevent 82 &
#script:
#- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

#sdk_components:
#- build-tools-19.0.3
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
script:
#- ./gradlew clean build
- ./gradlew clean build connectedAndroidTest
on:
  branch: dev
